# This file was generated by GoReleaser. DO NOT EDIT.
class ApiScenario < Formula
  desc "Scenario API testing from the command line."
  homepage "https://github.com/thomaspoignant/api-scenario"
  version "0.0.1"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/thomaspoignant/api-scenario/releases/download/v0.0.1/api-scenario_0.0.1_Darwin_x86_64.tar.gz"
    sha256 "bf1b39f2d115d9e7ec9223102f83140f944f2b8416446eafd165fa0a140142d2"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/thomaspoignant/api-scenario/releases/download/v0.0.1/api-scenario_0.0.1_Linux_x86_64.tar.gz"
      sha256 "ba3f531ed2333f10c270857468610a57c010331d7431e351161f7042e1035e5b"
    end
  end

  def install
    bin.install "api-scenario"
  end

  def caveats; <<~EOS
    Run api-scenario --help to see usage.
  EOS
  end
end
