# This file was generated by GoReleaser. DO NOT EDIT.
class ApiScenario < Formula
  desc "Scenario API testing from the command line."
  homepage "https://github.com/thomaspoignant/api-scenario"
  version "0.0.1"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/thomaspoignant/api-scenario/releases/download/v0.0.1/api-scenario_0.0.1_Darwin_x86_64.tar.gz"
    sha256 "07957f6e39da82479b253a70f68e0a617d699eed8b00e188ad4036059b4a8bf7"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/thomaspoignant/api-scenario/releases/download/v0.0.1/api-scenario_0.0.1_Linux_x86_64.tar.gz"
      sha256 "edf761ca28da0e27431a4f4d5f8e426ff789cf4c67409c4c46f21fb120509d94"
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/thomaspoignant/api-scenario/releases/download/v0.0.1/api-scenario_0.0.1_Linux_arm64.tar.gz"
        sha256 "01b23721eb7b0271155be528f95d70b7c1ea79cc0b71c624ec321678254824f6"
      else
        url "https://github.com/thomaspoignant/api-scenario/releases/download/v0.0.1/api-scenario_0.0.1_Linux_armv6.tar.gz"
        sha256 "20a8d2bad7d1c37e3d517987bd906e17f356de52eb608906ef9e49eed4aef1d1"
      end
    end
  end

  def install
    bin.install "api-scenario"
  end

  def caveats; <<~EOS
    Run api-scenario --help to see usage.
  EOS
  end
end
