# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GoFeatureFlagLint < Formula
  desc "A command line tool to lint your feature flag configuration file"
  homepage "https://gofeatureflag.org"
  version "1.2.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/thomaspoignant/go-feature-flag/releases/download/v1.2.1/go-feature-flag-lint_1.2.1_Darwin_x86_64.tar.gz"
      sha256 "202bdb9b6c4908f29c311ae8a9256e1d7315f703566ba717c7b553eb91d935c8"

      def install
        bin.install "go-feature-flag-lint"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/thomaspoignant/go-feature-flag/releases/download/v1.2.1/go-feature-flag-lint_1.2.1_Darwin_arm64.tar.gz"
      sha256 "06903c0e4bc83b3464245f7e8fabbe2c2ce37de241b7a07c69ca6b389f9e7fda"

      def install
        bin.install "go-feature-flag-lint"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/thomaspoignant/go-feature-flag/releases/download/v1.2.1/go-feature-flag-lint_1.2.1_Linux_x86_64.tar.gz"
      sha256 "cb6218afd045eb5eeee5842881fef2b39d05c8fdabee7bfc1d1c41541cbf9398"

      def install
        bin.install "go-feature-flag-lint"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/thomaspoignant/go-feature-flag/releases/download/v1.2.1/go-feature-flag-lint_1.2.1_Linux_arm64.tar.gz"
      sha256 "19d9303f0a52e98f9ea42c5b5506df22edf4888c47317243fafeb4e1d172d579"

      def install
        bin.install "go-feature-flag-lint"
      end
    end
  end

  def caveats
    <<~EOS
      A command line tool to lint your feature flag configuration file
    EOS
  end
end
