# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GoFeatureFlagCli < Formula
  desc "A command line tool to manage GO Feature Flag from your terminal"
  homepage "https://gofeatureflag.org/docs/tooling/cli"
  version "1.39.0"

  on_macos do
    on_intel do
      url "https://github.com/thomaspoignant/go-feature-flag/releases/download/v1.39.0/go-feature-flag-cli_1.39.0_Darwin_x86_64.tar.gz"
      sha256 "b9643c97ed66dc474de9ee03c3ce08e0b6e398abaa7d7e886bd64b24c2a8b489"

      def install
        bin.install "go-feature-flag-cli"
      end
    end
    on_arm do
      url "https://github.com/thomaspoignant/go-feature-flag/releases/download/v1.39.0/go-feature-flag-cli_1.39.0_Darwin_arm64.tar.gz"
      sha256 "6f8b48e9dd0af2d944acc87033edea0faa41919e747bb863935503d25bf13d27"

      def install
        bin.install "go-feature-flag-cli"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/thomaspoignant/go-feature-flag/releases/download/v1.39.0/go-feature-flag-cli_1.39.0_Linux_x86_64.tar.gz"
        sha256 "a73b4cc3e9808a3f24fae9cde3e0c190985ae71dd7ad85dc5201f84212e1ba8b"

        def install
          bin.install "go-feature-flag-cli"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/thomaspoignant/go-feature-flag/releases/download/v1.39.0/go-feature-flag-cli_1.39.0_Linux_arm64.tar.gz"
        sha256 "77d7e4f8c0cd85f0abf371b90acf9379e1aa8e6249be00b6605edd3e124baa21"

        def install
          bin.install "go-feature-flag-cli"
        end
      end
    end
  end

  def caveats
    <<~EOS
      A command line tool to manage GO Feature Flag from your terminal
    EOS
  end
end
