# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GoFeatureFlagMigrationCli < Formula
  desc "A migration command line to move your feature flag configuration file from format GO Feature Flag v0.X to v1.X"
  homepage "https://github.com/thomaspoignant/go-feature-flag/cmd/migrationcli"
  version "1.27.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/thomaspoignant/go-feature-flag/releases/download/v1.27.0/go-feature-flag-migration-cli_1.27.0_Darwin_x86_64.tar.gz"
      sha256 "85d2a6c8894e241cfe6e06cd360a38c8367e8e8367c573d227768f538f4f261b"

      def install
        bin.install "go-feature-flag-migration-cli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/thomaspoignant/go-feature-flag/releases/download/v1.27.0/go-feature-flag-migration-cli_1.27.0_Darwin_arm64.tar.gz"
      sha256 "2ed5e11a08e03e14d670945fb997451f409663722299f5e5515b89a5d1703245"

      def install
        bin.install "go-feature-flag-migration-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/thomaspoignant/go-feature-flag/releases/download/v1.27.0/go-feature-flag-migration-cli_1.27.0_Linux_x86_64.tar.gz"
      sha256 "bff40131aab33b9e11b04ff0d4f05940f955e1affa77633bd8ff666ccfb7f1f7"

      def install
        bin.install "go-feature-flag-migration-cli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/thomaspoignant/go-feature-flag/releases/download/v1.27.0/go-feature-flag-migration-cli_1.27.0_Linux_arm64.tar.gz"
      sha256 "784be12984222661dfee827b566e66535699b6da59f38b910a3e9d8cce678d04"

      def install
        bin.install "go-feature-flag-migration-cli"
      end
    end
  end

  def caveats
    <<~EOS
      A migration command line to move your feature flag configuration file from format GO Feature Flag v0.X to v1.X
    EOS
  end
end
