# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GoFeatureFlagLintCli < Formula
  desc "A command line tool to lint your feature flag configuration file"
  homepage "https://gofeatureflag.org"
  version "1.2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/thomaspoignant/go-feature-flag/releases/download/v1.2.0/go-feature-flag-lint-cli_1.2.0_Darwin_x86_64.tar.gz"
      sha256 "cf80f7768785bb45ad40f7eed82ab1ad83e42665b82bf6d63c8cc3ce13f9f27b"

      def install
        bin.install "go-feature-flag-lint-cli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/thomaspoignant/go-feature-flag/releases/download/v1.2.0/go-feature-flag-lint-cli_1.2.0_Darwin_arm64.tar.gz"
      sha256 "8f39accf450c1652ba27d3f1c631b721d8376e6d3265f7cbab0aa6839ce21ed3"

      def install
        bin.install "go-feature-flag-lint-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/thomaspoignant/go-feature-flag/releases/download/v1.2.0/go-feature-flag-lint-cli_1.2.0_Linux_x86_64.tar.gz"
      sha256 "8bd2e0816d60c62935f9ea1a626127575dde6dd94219859d3cf2208139fd781e"

      def install
        bin.install "go-feature-flag-lint-cli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/thomaspoignant/go-feature-flag/releases/download/v1.2.0/go-feature-flag-lint-cli_1.2.0_Linux_arm64.tar.gz"
      sha256 "91b30aa239ff4b547495768a7ca5d8ae105786bee3baba5a19b45cbdde13f764"

      def install
        bin.install "go-feature-flag-lint-cli"
      end
    end
  end

  def caveats
    <<~EOS
      A command line tool to lint your feature flag configuration file
    EOS
  end
end
