# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GoFeatureFlagLint < Formula
  desc "A command line tool to lint your feature flag configuration file"
  homepage "https://gofeatureflag.org/docs/tooling/linter"
  version "1.40.0"

  on_macos do
    on_intel do
      url "https://github.com/thomaspoignant/go-feature-flag/releases/download/v1.40.0/go-feature-flag-lint_1.40.0_Darwin_x86_64.tar.gz"
      sha256 "9dfb638804688728a20afa8e41e1fd5f53a56b4c3f0c44901aeddfce93403daa"

      def install
        bin.install "go-feature-flag-lint"
      end
    end
    on_arm do
      url "https://github.com/thomaspoignant/go-feature-flag/releases/download/v1.40.0/go-feature-flag-lint_1.40.0_Darwin_arm64.tar.gz"
      sha256 "1c21549a4679ce9c14ae78bf626fe43958797dd1f37c2c99cc80cd913ecd66fa"

      def install
        bin.install "go-feature-flag-lint"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/thomaspoignant/go-feature-flag/releases/download/v1.40.0/go-feature-flag-lint_1.40.0_Linux_x86_64.tar.gz"
        sha256 "dd6c5f409d63ed1c238797a6782ba91d7aae0be0ae85f3af72b4286716619dd0"

        def install
          bin.install "go-feature-flag-lint"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/thomaspoignant/go-feature-flag/releases/download/v1.40.0/go-feature-flag-lint_1.40.0_Linux_arm64.tar.gz"
        sha256 "f5438e505e878440c03a2729d050031a1ddce3262db922bd2099b92bbd41e92a"

        def install
          bin.install "go-feature-flag-lint"
        end
      end
    end
  end

  def caveats
    <<~EOS
      A command line tool to lint your feature flag configuration file
    EOS
  end
end
