# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GoFeatureFlagRelayProxy < Formula
  desc "A stand alone server to run GO Feature Flag"
  homepage "https://gofeatureflag.org"
  version "1.20.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/thomaspoignant/go-feature-flag/releases/download/v1.20.2/go-feature-flag-relay-proxy_1.20.2_Darwin_x86_64.tar.gz"
      sha256 "f3590ae3caf4b0289b8b5e8b90491eae1ea63dc02f12e0c5bdeb77039a38bf86"

      def install
        bin.install "go-feature-flag-relay-proxy"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/thomaspoignant/go-feature-flag/releases/download/v1.20.2/go-feature-flag-relay-proxy_1.20.2_Darwin_arm64.tar.gz"
      sha256 "79ca87c06f7fd30ba06a9686391ef00a0fddd660d9eb1e94f9f62c70200c6c70"

      def install
        bin.install "go-feature-flag-relay-proxy"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/thomaspoignant/go-feature-flag/releases/download/v1.20.2/go-feature-flag-relay-proxy_1.20.2_Linux_x86_64.tar.gz"
      sha256 "d2ac11fcf7c6e3f1a5b5724e63d3494f434681623629310f88668f9436d45863"

      def install
        bin.install "go-feature-flag-relay-proxy"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/thomaspoignant/go-feature-flag/releases/download/v1.20.2/go-feature-flag-relay-proxy_1.20.2_Linux_arm64.tar.gz"
      sha256 "93757cc0379e916b9d32ef36e193d837b481b230a4c39ecc324dc7660b557e20"

      def install
        bin.install "go-feature-flag-relay-proxy"
      end
    end
  end

  def caveats
    <<~EOS
      A stand alone server to run GO Feature Flag
    EOS
  end
end
