# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GoFeatureFlagMigrationCli < Formula
  desc "A migration command line to move your feature flag configuration file from format GO Feature Flag v0.X to v1.X"
  homepage "https://github.com/thomaspoignant/go-feature-flag/cmd/migrationcli"
  version "1.12.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/thomaspoignant/go-feature-flag/releases/download/v1.12.0/go-feature-flag-migration-cli_1.12.0_Darwin_arm64.tar.gz"
      sha256 "fd44934bbeb8ef22476c4617bbe060dc5f74250e84f94d96768deb4bfaf48f9d"

      def install
        bin.install "go-feature-flag-migration-cli"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/thomaspoignant/go-feature-flag/releases/download/v1.12.0/go-feature-flag-migration-cli_1.12.0_Darwin_x86_64.tar.gz"
      sha256 "4328ef11cd73fdde85269db5a9af585b4447a27a25de50685fb0ad8cfe6dd9d2"

      def install
        bin.install "go-feature-flag-migration-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/thomaspoignant/go-feature-flag/releases/download/v1.12.0/go-feature-flag-migration-cli_1.12.0_Linux_x86_64.tar.gz"
      sha256 "2be9443863f3bc32ac7116d66ac76a917ae28c30f72cc06fa249744fded8e675"

      def install
        bin.install "go-feature-flag-migration-cli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/thomaspoignant/go-feature-flag/releases/download/v1.12.0/go-feature-flag-migration-cli_1.12.0_Linux_arm64.tar.gz"
      sha256 "ef235e8db285813b187bc8ec4d1c08c03ea772fbf64829941970342205126a65"

      def install
        bin.install "go-feature-flag-migration-cli"
      end
    end
  end

  def caveats
    <<~EOS
      A migration command line to move your feature flag configuration file from format GO Feature Flag v0.X to v1.X
    EOS
  end
end
