# This file was generated by GoReleaser. DO NOT EDIT.
class YamllintCheckstyle < Formula
  desc "Convert yamllint output to checkstyle format."
  homepage "https://github.com/thomaspoignant/yamllint-checkstyle"
  version "1.0.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/thomaspoignant/yamllint-checkstyle/releases/download/v1.0.0/yamllint-checkstyle_1.0.0_Darwin_x86_64.tar.gz"
    sha256 "0ee895cc36e7c951d88656488e430b678248bee49e9cf946e39112a8fe20c4b0"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/thomaspoignant/yamllint-checkstyle/releases/download/v1.0.0/yamllint-checkstyle_1.0.0_Linux_x86_64.tar.gz"
      sha256 "6d0fb08d22c7905faa3d72c9e2baae4c112c94ddbe3f16313fa5c3660025987e"
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/thomaspoignant/yamllint-checkstyle/releases/download/v1.0.0/yamllint-checkstyle_1.0.0_Linux_arm64.tar.gz"
        sha256 "f047e1a4f0efb7a9539db93a6bea4909b6d165ab5a0cda755bd1bd6c2f517bfb"
      else
        url "https://github.com/thomaspoignant/yamllint-checkstyle/releases/download/v1.0.0/yamllint-checkstyle_1.0.0_Linux_armv6.tar.gz"
        sha256 "6bee41259e79ed472a1778928ece399da4bf84f0350d45e69d29426e98da583b"
      end
    end
  end

  def install
    bin.install "yamllint-checkstyle"
  end

  def caveats; <<~EOS
    Run yamllint-checkstyle
  EOS
  end
end
