# This file was generated by GoReleaser. DO NOT EDIT.
class YamllintCheckstyle < Formula
  desc "Convert yamllint output to checkstyle format."
  homepage "https://github.com/thomaspoignant/yamllint-checkstyle"
  version "0.0.3"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/thomaspoignant/yamllint-checkstyle/releases/download/v0.0.3/yamllint-checkstyle_0.0.3_Darwin_x86_64.tar.gz"
    sha256 "eb7c98570810f83dad741cec560a3c64439002368e124dfe9d4b8be7d7aeddd5"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/thomaspoignant/yamllint-checkstyle/releases/download/v0.0.3/yamllint-checkstyle_0.0.3_Linux_x86_64.tar.gz"
      sha256 "d5d07e9739d35c4f6be2109011d73d3a37b57f4cfc9c8284cf397e5519fbe975"
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/thomaspoignant/yamllint-checkstyle/releases/download/v0.0.3/yamllint-checkstyle_0.0.3_Linux_arm64.tar.gz"
        sha256 "cda2321eabec677e825f60f3cf6e608a3db5f61191b7918485bce9c7e75ba96d"
      else
        url "https://github.com/thomaspoignant/yamllint-checkstyle/releases/download/v0.0.3/yamllint-checkstyle_0.0.3_Linux_armv6.tar.gz"
        sha256 "7386de2c9d9dcfa1059c57a7683f0feb65d9d8a6a1028640cafc6437ffc3e4f2"
      end
    end
  end

  def install
    bin.install "yamllint-checkstyle"
  end

  def caveats; <<~EOS
    Run yamllint-checkstyle
  EOS
  end
end
