# This file was generated by GoReleaser. DO NOT EDIT.
cask "go-feature-flag-lint" do
  desc "A command line tool to lint your feature flag configuration file"
  homepage "https://gofeatureflag.org/docs/tooling/linter"
  version "1.45.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "go-feature-flag-lint"

  on_macos do
    on_intel do
      url "https://github.com/thomaspoignant/go-feature-flag/releases/download/v1.45.2/go-feature-flag-lint_1.45.2_Darwin_x86_64.tar.gz"
      sha256 "4c147b637d45d94302064cb1a556633581d85f876db940c5830cca0d7c8c417f"
    end
    on_arm do
      url "https://github.com/thomaspoignant/go-feature-flag/releases/download/v1.45.2/go-feature-flag-lint_1.45.2_Darwin_arm64.tar.gz"
      sha256 "2f7af59241f06cbb96359712fe45bdb1e56a64b75e04a45ba73a7519249cb542"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/thomaspoignant/go-feature-flag/releases/download/v1.45.2/go-feature-flag-lint_1.45.2_Linux_x86_64.tar.gz"
      sha256 "8f250aa6171aa9bc702648e091ce69037836fe76b9525cc16e074391812296aa"
    end
    on_arm do
      url "https://github.com/thomaspoignant/go-feature-flag/releases/download/v1.45.2/go-feature-flag-lint_1.45.2_Linux_arm64.tar.gz"
      sha256 "6edfebc460aff04eb577e1b009c569c6d1571f351762816c25b14afdf6a33ccb"
    end
  end

  caveats do
    "A command line tool to lint your feature flag configuration file"
  end

  # No zap stanza required
end
