# This file was generated by GoReleaser. DO NOT EDIT.
cask "go-feature-flag-lint" do
  name "go-feature-flag-lint"
  desc "A command line tool to lint your feature flag configuration file"
  homepage "https://gofeatureflag.org/docs/tooling/linter"
  version "1.51.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "go-feature-flag-lint"

  on_macos do
    on_intel do
      url "https://github.com/thomaspoignant/go-feature-flag/releases/download/v#{version}/go-feature-flag-lint_#{version}_Darwin_x86_64.tar.gz"
      sha256 "1067ad449002378605dbb05d0b7917691262587d528f7bca17ce627cd8198dbb"
    end
    on_arm do
      url "https://github.com/thomaspoignant/go-feature-flag/releases/download/v#{version}/go-feature-flag-lint_#{version}_Darwin_arm64.tar.gz"
      sha256 "d0ba5facf6eb8a4323a86bdb7bbfc1b420f37448cb053f439894067f525cf06d"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/thomaspoignant/go-feature-flag/releases/download/v#{version}/go-feature-flag-lint_#{version}_Linux_x86_64.tar.gz"
      sha256 "2da6d5277701b6b78b29a22585615936e4acd21d02ada30c3bd5c866f172fd3d"
    end
    on_arm do
      url "https://github.com/thomaspoignant/go-feature-flag/releases/download/v#{version}/go-feature-flag-lint_#{version}_Linux_arm64.tar.gz"
      sha256 "15de56e2ad8cc034f32e75668ca725c8f85796ba4b39be6d3ace1a3bdaa0ec8d"
    end
  end

  caveats do
    "A command line tool to lint your feature flag configuration file"
  end

  # No zap stanza required
end
