# This file was generated by GoReleaser. DO NOT EDIT.
cask "go-feature-flag-relay-proxy" do
  version "1.55.3"

  on_macos do
    on_arm do
      sha256 "5fe57e629352ef0a506dc24eff03d21cec47c911f2bb41865aad27b6d1e5a138"
      url "https://github.com/thomaspoignant/go-feature-flag/releases/download/v#{version}/go-feature-flag-relay-proxy_#{version}_Darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "0c7acdf5128879108fd76205eb798cabc2f9f4783d47d8f4f0bd3f1db9ed1031"
      url "https://github.com/thomaspoignant/go-feature-flag/releases/download/v#{version}/go-feature-flag-relay-proxy_#{version}_Darwin_x86_64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "94c71b01697d48be8973a62175633932d6d186fb7acd4fd158bb88231a9de33f"
      url "https://github.com/thomaspoignant/go-feature-flag/releases/download/v#{version}/go-feature-flag-relay-proxy_#{version}_Linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "c3fe963c3328873c86993d5f7b3c151dc4d2c0dc7833332708779043fbd93ad9"
      url "https://github.com/thomaspoignant/go-feature-flag/releases/download/v#{version}/go-feature-flag-relay-proxy_#{version}_Linux_x86_64.tar.gz"
    end
  end

  name "go-feature-flag-relay-proxy"
  desc "A stand alone server to run GO Feature Flag"
  homepage "https://gofeatureflag.org/docs/relay_proxy"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "go-feature-flag-relay-proxy"

  # No zap stanza required

  caveats <<~EOS
    A stand alone server to run GO Feature Flag
  EOS
end
