# This file was generated by GoReleaser. DO NOT EDIT.
cask "go-feature-flag-lint" do
  desc "A command line tool to lint your feature flag configuration file"
  homepage "https://gofeatureflag.org/docs/tooling/linter"
  version "1.45.5"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "go-feature-flag-lint"

  on_macos do
    on_intel do
      url "https://github.com/thomaspoignant/go-feature-flag/releases/download/v1.45.5/go-feature-flag-lint_1.45.5_Darwin_x86_64.tar.gz"
      sha256 "49af9e1add3380e30756f2a1cc7770b7641785b6e08f7400796208e25bc8844c"
    end
    on_arm do
      url "https://github.com/thomaspoignant/go-feature-flag/releases/download/v1.45.5/go-feature-flag-lint_1.45.5_Darwin_arm64.tar.gz"
      sha256 "1a0315624601fe8c1813442af36a98e3aa3570146ca0a653734dabcecb2ee93e"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/thomaspoignant/go-feature-flag/releases/download/v1.45.5/go-feature-flag-lint_1.45.5_Linux_x86_64.tar.gz"
      sha256 "7513c177d39386cd464834dde417fc87a035c229b34034ab23f53ebe9723c6a1"
    end
    on_arm do
      url "https://github.com/thomaspoignant/go-feature-flag/releases/download/v1.45.5/go-feature-flag-lint_1.45.5_Linux_arm64.tar.gz"
      sha256 "cdd16229b38e110b580a0c45ae72d85145c019105ff6a708816f3d17c321458f"
    end
  end

  caveats do
    "A command line tool to lint your feature flag configuration file"
  end

  # No zap stanza required
end
