# This file was generated by GoReleaser. DO NOT EDIT.
cask "go-feature-flag" do
  version "1.54.0"

  on_macos do
    on_intel do
      sha256 "0aa6890ef8753693bb62129d31e116aeb0199ba1f851d3e481dc716f52f40a7c"
      url "https://github.com/thomaspoignant/go-feature-flag/releases/download/v#{version}/go-feature-flag_#{version}_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "96856551c00f99bdb0b43f8044d26c77fed41fa71f4c3e80ffd8c2d4f7411f50"
      url "https://github.com/thomaspoignant/go-feature-flag/releases/download/v#{version}/go-feature-flag_#{version}_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "d56901395475f98569d9e8ba5f740ee1367a7ca6674cb74fc5f6217069dd3a73"
      url "https://github.com/thomaspoignant/go-feature-flag/releases/download/v#{version}/go-feature-flag_#{version}_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "fac880e413f4650a9849ce00cdc6eaf156955acbb00bd9a46fcdf4265a8d4ee3"
      url "https://github.com/thomaspoignant/go-feature-flag/releases/download/v#{version}/go-feature-flag_#{version}_Linux_arm64.tar.gz"
    end
  end

  name "go-feature-flag"
  desc "A stand alone server to run GO Feature Flag"
  homepage "https://gofeatureflag.org/docs/relay_proxy"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "go-feature-flag"

  # No zap stanza required

  caveats <<~EOS
    A stand alone server to run GO Feature Flag
  EOS
end
