# This file was generated by GoReleaser. DO NOT EDIT.
cask "go-feature-flag" do
  name "go-feature-flag"
  desc "A stand alone server to run GO Feature Flag"
  homepage "https://gofeatureflag.org/docs/relay_proxy"
  version "1.47.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "go-feature-flag"

  on_macos do
    on_intel do
      url "https://github.com/thomaspoignant/go-feature-flag/releases/download/v#{version}/go-feature-flag_#{version}_Darwin_x86_64.tar.gz"
      sha256 "97571a0510d17f65b39a11672464504118bfcd02f382006affe0eb8ae761a65e"
    end
    on_arm do
      url "https://github.com/thomaspoignant/go-feature-flag/releases/download/v#{version}/go-feature-flag_#{version}_Darwin_arm64.tar.gz"
      sha256 "9ee5b00112a9761227b7869c154f67881223813dd7043e346709ceacd80a19e9"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/thomaspoignant/go-feature-flag/releases/download/v#{version}/go-feature-flag_#{version}_Linux_x86_64.tar.gz"
      sha256 "c0873ad88d13c4dd11cb542ba8b16634782f00a1c30e1d83fb20f000e0b6b705"
    end
    on_arm do
      url "https://github.com/thomaspoignant/go-feature-flag/releases/download/v#{version}/go-feature-flag_#{version}_Linux_arm64.tar.gz"
      sha256 "d9a36eef4a1baa115bbda662b08155c062bef25bd568a003970256be8788fdae"
    end
  end

  caveats do
    "A stand alone server to run GO Feature Flag"
  end

  # No zap stanza required
end
