# This file was generated by GoReleaser. DO NOT EDIT.
cask "go-feature-flag" do
  name "go-feature-flag"
  desc "A stand alone server to run GO Feature Flag"
  homepage "https://gofeatureflag.org/docs/relay_proxy"
  version "1.48.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "go-feature-flag"

  on_macos do
    on_intel do
      url "https://github.com/thomaspoignant/go-feature-flag/releases/download/v#{version}/go-feature-flag_#{version}_Darwin_x86_64.tar.gz"
      sha256 "d5d57aa08c0c2e5e2167d40c3c1ce468bb60a150fe532533c380a66c579b1684"
    end
    on_arm do
      url "https://github.com/thomaspoignant/go-feature-flag/releases/download/v#{version}/go-feature-flag_#{version}_Darwin_arm64.tar.gz"
      sha256 "5959f3d56ea1c3c77e180a6af8a27b524786b503bb47364664c61d459d598722"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/thomaspoignant/go-feature-flag/releases/download/v#{version}/go-feature-flag_#{version}_Linux_x86_64.tar.gz"
      sha256 "3320cbb9fac3862897a9629d9f5489a83dee650d0a7aac21e4f531ac84d60e3b"
    end
    on_arm do
      url "https://github.com/thomaspoignant/go-feature-flag/releases/download/v#{version}/go-feature-flag_#{version}_Linux_arm64.tar.gz"
      sha256 "f28bf6679cbe776de8a4b3453731760d4b93f0a49b7f14486a8b5fcadad87748"
    end
  end

  caveats do
    "A stand alone server to run GO Feature Flag"
  end

  # No zap stanza required
end
