# This file was generated by GoReleaser. DO NOT EDIT.
cask "go-feature-flag-relay-proxy" do
  name "go-feature-flag-relay-proxy"
  desc "A stand alone server to run GO Feature Flag"
  homepage "https://gofeatureflag.org/docs/relay_proxy"
  version "1.49.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "go-feature-flag-relay-proxy"

  on_macos do
    on_intel do
      url "https://github.com/thomaspoignant/go-feature-flag/releases/download/v#{version}/go-feature-flag-relay-proxy_#{version}_Darwin_x86_64.tar.gz"
      sha256 "c03a89506500328f8a7ebe1e6dd35174de25ea751f8a887d1c20543334f3f7b8"
    end
    on_arm do
      url "https://github.com/thomaspoignant/go-feature-flag/releases/download/v#{version}/go-feature-flag-relay-proxy_#{version}_Darwin_arm64.tar.gz"
      sha256 "a01f377a66412138aa4f92901b631cdc7a33b28cd253ccf3a147beee301520b4"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/thomaspoignant/go-feature-flag/releases/download/v#{version}/go-feature-flag-relay-proxy_#{version}_Linux_x86_64.tar.gz"
      sha256 "965c8b4b5678f9ee4dfecb2c0c04637cc7906d82469147f22013720eb49dfa0e"
    end
    on_arm do
      url "https://github.com/thomaspoignant/go-feature-flag/releases/download/v#{version}/go-feature-flag-relay-proxy_#{version}_Linux_arm64.tar.gz"
      sha256 "7a9cd38195e6ed7cc4ceee3aabe674feb96cb097c38105c50084e1f24f1c07da"
    end
  end

  caveats do
    "A stand alone server to run GO Feature Flag"
  end

  # No zap stanza required
end
