# This file was generated by GoReleaser. DO NOT EDIT.
cask "go-feature-flag-cli" do
  name "go-feature-flag-cli"
  desc "A command line tool to manage GO Feature Flag from your terminal"
  homepage "https://gofeatureflag.org/docs/tooling/cli"
  version "1.46.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "go-feature-flag-cli"

  on_macos do
    on_intel do
      url "https://github.com/thomaspoignant/go-feature-flag/releases/download/v#{version}/go-feature-flag-cli_#{version}_Darwin_x86_64.tar.gz"
      sha256 "8d8d7e1368bcf73e6da99a8cdb2e85b3a32c5248bb5be5c47f09217dadece64f"
    end
    on_arm do
      url "https://github.com/thomaspoignant/go-feature-flag/releases/download/v#{version}/go-feature-flag-cli_#{version}_Darwin_arm64.tar.gz"
      sha256 "7cd5c2113a66f20ec2c962061a9fe50205dda8c4520c1c0aa38c9cd8889f59d3"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/thomaspoignant/go-feature-flag/releases/download/v#{version}/go-feature-flag-cli_#{version}_Linux_x86_64.tar.gz"
      sha256 "737fcd4d8f100fed0f2ff1c7e13766147199a0ae1e16470cf3decd32b74fc43a"
    end
    on_arm do
      url "https://github.com/thomaspoignant/go-feature-flag/releases/download/v#{version}/go-feature-flag-cli_#{version}_Linux_arm64.tar.gz"
      sha256 "537f29e259fda4755787c843b84c284da2ba30397277abe55f697539e64ac81b"
    end
  end

  caveats do
    "A command line tool to manage GO Feature Flag from your terminal"
  end

  # No zap stanza required
end
