# This file was generated by GoReleaser. DO NOT EDIT.
cask "go-feature-flag-relay-proxy" do
  desc "A stand alone server to run GO Feature Flag"
  homepage "https://gofeatureflag.org/docs/relay_proxy"
  version "1.45.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "go-feature-flag-relay-proxy"

  on_macos do
    on_intel do
      url "https://github.com/thomaspoignant/go-feature-flag/releases/download/v1.45.1/go-feature-flag-relay-proxy_1.45.1_Darwin_x86_64.tar.gz"
      sha256 "e2d0c744be851ac99ca9e0fa5070cfd35543a4d20a4d9b727d16a01dacfcd41e"
    end
    on_arm do
      url "https://github.com/thomaspoignant/go-feature-flag/releases/download/v1.45.1/go-feature-flag-relay-proxy_1.45.1_Darwin_arm64.tar.gz"
      sha256 "da54135a04dba6da88ce9838fc56566ab30800097beb7e559402b7837f92a992"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/thomaspoignant/go-feature-flag/releases/download/v1.45.1/go-feature-flag-relay-proxy_1.45.1_Linux_x86_64.tar.gz"
      sha256 "f9c335fda324a321fd9aa35e3377fb8a28fc29d366c462d5738fb106d7d89fb4"
    end
    on_arm do
      url "https://github.com/thomaspoignant/go-feature-flag/releases/download/v1.45.1/go-feature-flag-relay-proxy_1.45.1_Linux_arm64.tar.gz"
      sha256 "b27b898e9f6ab7a194db570499957f3de820fe5ecb3ea21edae4f220393ff588"
    end
  end

  caveats do
    "A stand alone server to run GO Feature Flag"
  end

  # No zap stanza required
end
